### ISSUE TITLE
[PE-D][Tester A] Should not allow last met date to be before the client's birthday

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W12-1/tp#125]
Description:
  - When using the "met" command or the "edit d/dob" command, the system currently allows users to make the last met date before the birthday which should not be possible.

Replication:
  - Start up with default json file.
  - Enter commands:
      - met 1 d/1950-02-03

Negative Impact:
  - Can be very confusing on the users if you last met someone before they were born.

Suggested Solution:
  - When editing a client's dob, ensure that this date can not be after the last met date.
  - When updating a client's last met date, ensure that this date can not be before the birthday.
  - Produce error message if invalid attempts are made.

Screenshots:

![Screenshot 2024-04-05 at 4.18.36 PM.png](https://raw.githubusercontent.com/alfaloo/ped/main/files/65288a85-c0bf-4b8d-9b10-a9b5c6dd0a90.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: alfaloo/ped#1

**Comment by ReganChoy** [comment]
The intended feature of Last Met is to allow users to remind themselves on who they should meet. We give users the flexibility to set whatever date they want to be reminded.

Certain clients like newborn babies may be only a few days old. Users can set the Last Met to be earlier than the date of birth so they can bypass the standard Last Met overdue period they set. Otherwise, they would need to change the Last Met overdue period to cater to these outliers.
